name: Pilot Images

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      push:
        description: Push images to registries
        type: boolean
        default: false

jobs:
  postgresql:
    uses: ./.github/workflows/docker-build.yml
    with:
      image_name: postgresql-lsio
      dockerfile: examples/postgresql/Dockerfile
      context: examples/postgresql
      platforms: linux/amd64,linux/arm64,linux/arm/v7
      push: ${{ github.event_name == 'workflow_dispatch' && inputs.push }}
    secrets: inherit

  mariadb:
    uses: ./.github/workflows/docker-build.yml
    with:
      image_name: mariadb-lsio
      dockerfile: examples/mariadb/Dockerfile
      context: examples/mariadb
      platforms: linux/amd64,linux/arm64,linux/arm/v7
      push: ${{ github.event_name == 'workflow_dispatch' && inputs.push }}
    secrets: inherit
